admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - address:
        socket_address:
          address: "::"
          port_value: 8080
      additional_addresses:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/v1/"
                          route:
                            cluster: openai
                            host_rewrite_literal: "api.openai.com"
                      typed_per_filter_config:
                        envoy.filters.http.cors:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                          allow_credentials: true
                          allow_headers: "*"
                          allow_methods: "GET,POST,OPTIONS"
                          allow_origin_string_match:
                            - safe_regex:
                                regex: https?://localhost(:\d+)?
                            - safe_regex:
                                regex: https?://127.0.0.1(:\d+)?
                            - safe_regex:
                                regex: https?://\[::1\](:\d+)?
                          allow_private_network_access: true
                          max_age: "86400"
                http_filters:
                  - name: envoy.filters.http.health_check
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                      pass_through_mode: false
                      headers:
                        - name: ":method"
                          string_match:
                            exact: "GET"
                        - name: ":path"
                          string_match:
                            exact: "/ping"
                  - name: envoy.filters.http.header_to_metadata
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
                      request_rules:
                        # Make request path available for ext_authz
                        - header: :path
                          on_header_present:
                            metadata_namespace: envoy.filters.http.ext_authz
                            key: :path
                            type: STRING
                          remove: false
                  - name: extensions.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      grpc_service:
                        google_grpc:
                          target_uri: opa:9191
                          stat_prefix: ext_authz
                        timeout: 5s
                      failure_mode_allow: false
                      # Enable ext_authz only for OpenAI API /v1/ paths
                      filter_enabled_metadata:
                        filter: envoy.filters.http.ext_authz
                        path:
                          - key: :path
                        value:
                          string_match:
                            prefix: /v1/
                      status_on_error:
                        code: 503
                      transport_api_version: V3
                      with_request_body:
                        max_request_bytes: 1048576
                        allow_partial_message: true
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: openai
      connect_timeout: 0.5s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: openai
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      protocol: TCP
                      address: api.openai.com
                      port_value: 443
      # https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: api.openai.com
          common_tls_context:
            validation_context:
              match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: api.openai.com
              trusted_ca:
                filename: /etc/ssl/certs/ca-certificates.crt
